package br.com.unikedin.model;

import java.util.ArrayList;
import java.util.List;

public enum Curso {
    SELECIONE("-- SELECIONE --"),
    ADMINISTRAÇÃO("ADMINISTRAÇÃO"),
    ARQUITETURAEURBANISMO("ARQUITETURA E URBANISMO"),
    AGRONOMIA("AGRONOMIA"),
    BIOTECNOLOGIA("BIOTECNOLOGIA"),
    CIÊNCIADACOMPUTACAO("CIÊNCIA DA COMPUTAÇÃO"),
    CIÊNCIASCONTABEIS("CIÊNCIAS CONTÁBEIS"),
    COMPUTACAO("COMPUTAÇÃO"),
    COMPUTAÇÃOEINFORMATICA("COMPUTAÇÃO E INFORMÁTICA"),
    DIREITO("DIREITO"),
    ECOLOGIA("ECOLOGIA"),
    ENGENHARIAAGRICOLAEAMBIENTAL("ENGENHARIA AGRÍCOLA E AMBIENTAL"),
    ENGENHARIAAMBIENTALESANITÁRIA("ENGENHARIA AMBIENTAL E SANITÁRIA"),
    ENGENHARIACIVIL("ENGENHARIA CIVIL"),
    ENGENHARIADECOMPUTACAO("ENGENHARIA DE COMPUTAÇÃO"),
    ENGENHARIADEENERGIA("ENGENHARIA DE ENERGIA"),
    ENGENHARIADEPETROLEO("ENGENHARIA DE PETRÓLEO"),
    ENGENHARIADEPRODUCAO("ENGENHARIA DE PRODUÇÃO"),
    ENGENHARIADESOFTWARE("ENGENHARIA DE SOFTWARE"),
    ENGENHARIAELETRICA("ENGENHARIA ELÉTRICA"),
    ENGENHARIAFLORESTAL("ENGENHARIA FLORESTAL"),
    ENGENHARIAMECANICA("ENGENHARIA MECÂNICA"),
    ENGENHARIAQUIMICA("ENGENHARIA QUÍMICA"),
    ENGENHARIADEPESCA("ENGENHARIA DE PESCA"),
    FISICA("FÍSICA"),
    INTERDISCIPLINAREMCIENCIAETECNOLOGIA("INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA"),
    INTERDISCIPLINAREMTECNOLOGIADAINFORMACAO("INTERDISCIPLINAR EM TECNOLOGIA DA INFORMAÇÃO"),
    INGLES("LETRAS/INGLÊS"),
    LIBRAS("LETRAS/LIBRAS"),
    PORTUGUES("LETRAS/PORTUGUÊS"),
    MATEMATICA("MATEMÁTICA"),
    MEDICINA("MEDICINA"),
    MEDICINAVETERINARIA("MEDICINA VETERINÁRIA"),
    PEDAGOGIA("PEDAGOGIA"),
    QUIMICA("QUÍMICA"),
    SISTEMASDEINFORMACAO("SISTEMAS DE INFORMAÇÃO"),
    ZOOTECNIA("ZOOTECNIA");

    private String nome;

    Curso(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }

    public static List<String> getNomes() {
        List<String> nomes = new ArrayList<>();
        for (Curso curso : Curso.values()) {
            nomes.add(curso.getNome());
        }
        return nomes;
    }
}
